### ISSUE TITLE
Missing tqdm when installing through conda

### ISSUE THREAD

**Issue by grst** [icbi-lab/scirpy#128]
I used the conda installation procedure as listed here:

```
###################################

(base) Federicos-MBP:Development fede$ conda create --name playground_scirpy scirpy
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/fede/miniconda3/envs/playground_scirpy

  added / updated specs:
    - scirpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anndata-0.7.1              |           py36_0         155 KB  conda-forge
    blosc-1.18.1               |       h4a8c4bd_0         859 KB  conda-forge
    cython-0.29.17             |   py36h0130604_0         2.1 MB  conda-forge
    glib-2.64.2                |       h577aef8_0         3.2 MB  conda-forge
    h5py-2.10.0                |nompi_py36h106b333_102        1020 KB  conda-forge
    importlib-metadata-1.6.0   |   py36h9f0ad1d_0          42 KB  conda-forge
    importlib_metadata-1.6.0   |                0           3 KB  conda-forge
    kiwisolver-1.2.0           |   py36h863e41a_0          57 KB  conda-forge
    legacy-api-wrap-1.2        |             py_0          18 KB  conda-forge
    libcxx-10.0.0              |       h1af66ff_2         1.0 MB  conda-forge
    llvm-openmp-10.0.0         |       h28b9765_0         268 KB  conda-forge
    llvmlite-0.31.0            |   py36hde82470_1         251 KB  conda-forge
    matplotlib-base-3.2.1      |   py36h83d3ec1_0         7.1 MB  conda-forge
    mock-3.0.5                 |   py36h9f0ad1d_1          44 KB  conda-forge
    nose-1.3.7                 |py36h9f0ad1d_1004         213 KB  conda-forge
    numba-0.48.0               |   py36h4f17bb1_0         3.2 MB  conda-forge
    numexpr-2.7.1              |   py36hcc1bba6_1         128 KB  conda-forge
    openssl-1.1.1g             |       h0b31af3_0         1.9 MB  conda-forge
    packaging-20.1             |             py_0          31 KB  conda-forge
    pandas-1.0.3               |   py36hcc1bba6_1        10.2 MB  conda-forge
    parasail-python-1.2        |   py36hfbae3c0_0         1.9 MB  bioconda
    pip-20.1                   |     pyh9f0ad1d_0         1.1 MB  conda-forge
    pycairo-1.19.1             |   py36h1ef2672_3          69 KB  conda-forge
    pyparsing-2.4.7            |     pyh9f0ad1d_0          60 KB  conda-forge
    pytables-3.6.1             |   py36h6f8395a_1         1.4 MB  conda-forge
    python-3.6.10              |h4334963_1011_cpython        20.2 MB  conda-forge
    python-igraph-0.8.2        |   py36hffd003b_0         2.0 MB  conda-forge
    python-levenshtein-0.12.0  |           py36_1          67 KB  bioconda
    pytz-2020.1                |     pyh9f0ad1d_0         227 KB  conda-forge
    scanpy-1.4.6               |             py_0         6.6 MB  bioconda
    scikit-learn-0.22.2.post1  |   py36h3dc85bc_0         6.4 MB  conda-forge
    scipy-1.4.1                |   py36h1dac7e4_3        19.0 MB  conda-forge
    scirpy-0.1.2               |             py_0          51 KB  bioconda
    seaborn-0.10.1             |             py_0         158 KB  conda-forge
    setuptools-46.1.3          |   py36h9f0ad1d_0         635 KB  conda-forge
    setuptools-scm-3.5.0       |             py_1          23 KB  conda-forge
    setuptools_scm-3.5.0       |                1           3 KB  conda-forge
    squarify-0.4.3             |             py_0           7 KB  conda-forge
    statsmodels-0.11.1         |   py36h37b9a7d_1         9.6 MB  conda-forge
    tbb-2019.9                 |       ha1b3eb9_1         157 KB  conda-forge
    tornado-6.0.4              |   py36h37b9a7d_1         639 KB  conda-forge
    umap-learn-0.4.2           |   py36h9f0ad1d_0         108 KB  conda-forge
    xz-5.2.5                   |       h0b31af3_0         266 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       102.3 MB

The following NEW packages will be INSTALLED:

  anndata            conda-forge/osx-64::anndata-0.7.1-py36_0
  blosc              conda-forge/osx-64::blosc-1.18.1-h4a8c4bd_0
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0b31af3_2
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.4.5.1-hecc5488_0
  cairo              conda-forge/osx-64::cairo-1.16.0-hec6a9b0_1003
  certifi            conda-forge/osx-64::certifi-2020.4.5.1-py36h9f0ad1d_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  cython             conda-forge/osx-64::cython-0.29.17-py36h0130604_0
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  fontconfig         conda-forge/osx-64::fontconfig-2.13.1-h6b1039f_1001
  freetype           conda-forge/osx-64::freetype-2.10.1-h8da9a1a_0
  get_version        conda-forge/noarch::get_version-2.1-py_1
  gettext            conda-forge/osx-64::gettext-0.19.8.1-h46ab8bc_1002
  glib               conda-forge/osx-64::glib-2.64.2-h577aef8_0
  gmp                conda-forge/osx-64::gmp-6.2.0-h4a8c4bd_2
  h5py               conda-forge/osx-64::h5py-2.10.0-nompi_py36h106b333_102
  hdf5               conda-forge/osx-64::hdf5-1.10.5-nompi_h3e39495_1104
  icu                conda-forge/osx-64::icu-64.2-h6de7cb9_1
  importlib-metadata conda-forge/osx-64::importlib-metadata-1.6.0-py36h9f0ad1d_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.6.0-0
  joblib             conda-forge/noarch::joblib-0.14.1-py_0
  kiwisolver         conda-forge/osx-64::kiwisolver-1.2.0-py36h863e41a_0
  legacy-api-wrap    conda-forge/noarch::legacy-api-wrap-1.2-py_0
  libblas            conda-forge/osx-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/osx-64::libcblas-3.8.0-16_openblas
  libcxx             conda-forge/osx-64::libcxx-10.0.0-h1af66ff_2
  libffi             bioconda/osx-64::libffi-3.2.1-1
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-2
  libiconv           conda-forge/osx-64::libiconv-1.15-h0b31af3_1006
  liblapack          conda-forge/osx-64::liblapack-3.8.0-16_openblas
  libllvm8           conda-forge/osx-64::libllvm8-8.0.1-h770b8ee_0
  libopenblas        conda-forge/osx-64::libopenblas-0.3.9-h3d69b6c_0
  libpng             conda-forge/osx-64::libpng-1.6.37-hbbe82c9_1
  libxml2            conda-forge/osx-64::libxml2-2.9.10-h53d96d6_0
  llvm-openmp        conda-forge/osx-64::llvm-openmp-10.0.0-h28b9765_0
  llvmlite           conda-forge/osx-64::llvmlite-0.31.0-py36hde82470_1
  matplotlib-base    conda-forge/osx-64::matplotlib-base-3.2.1-py36h83d3ec1_0
  mock               conda-forge/osx-64::mock-3.0.5-py36h9f0ad1d_1
  natsort            conda-forge/noarch::natsort-7.0.1-py_0
  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002
  networkx           conda-forge/noarch::networkx-2.4-py_1
  nose               conda-forge/osx-64::nose-1.3.7-py36h9f0ad1d_1004
  numba              conda-forge/osx-64::numba-0.48.0-py36h4f17bb1_0
  numexpr            conda-forge/osx-64::numexpr-2.7.1-py36hcc1bba6_1
  numpy              conda-forge/osx-64::numpy-1.18.1-py36hdc5ca10_1
  openssl            conda-forge/osx-64::openssl-1.1.1g-h0b31af3_0
  packaging          conda-forge/noarch::packaging-20.1-py_0
  pandas             conda-forge/osx-64::pandas-1.0.3-py36hcc1bba6_1
  parasail-python    bioconda/osx-64::parasail-python-1.2-py36hfbae3c0_0
  patsy              conda-forge/noarch::patsy-0.5.1-py_0
  pcre               conda-forge/osx-64::pcre-8.44-h4a8c4bd_0
  pip                conda-forge/noarch::pip-20.1-pyh9f0ad1d_0
  pixman             conda-forge/osx-64::pixman-0.38.0-h01d97ff_1003
  pycairo            conda-forge/osx-64::pycairo-1.19.1-py36h1ef2672_3
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pytables           conda-forge/osx-64::pytables-3.6.1-py36h6f8395a_1
  python             conda-forge/osx-64::python-3.6.10-h4334963_1011_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python-igraph      conda-forge/osx-64::python-igraph-0.8.2-py36hffd003b_0
  python-levenshtein bioconda/osx-64::python-levenshtein-0.12.0-py36_1
  python_abi         conda-forge/osx-64::python_abi-3.6-1_cp36m
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  readline           conda-forge/osx-64::readline-8.0-hcfe32e1_0
  scanpy             bioconda/noarch::scanpy-1.4.6-py_0
  scikit-learn       conda-forge/osx-64::scikit-learn-0.22.2.post1-py36h3dc85bc_0
  scipy              conda-forge/osx-64::scipy-1.4.1-py36h1dac7e4_3
  scirpy             bioconda/noarch::scirpy-0.1.2-py_0
  seaborn            conda-forge/noarch::seaborn-0.10.1-py_0
  setuptools         conda-forge/osx-64::setuptools-46.1.3-py36h9f0ad1d_0
  setuptools-scm     conda-forge/noarch::setuptools-scm-3.5.0-py_1
  setuptools_scm     conda-forge/noarch::setuptools_scm-3.5.0-1
  six                conda-forge/noarch::six-1.14.0-py_1
  sqlite             conda-forge/osx-64::sqlite-3.30.1-h93121df_0
  squarify           conda-forge/noarch::squarify-0.4.3-py_0
  statsmodels        conda-forge/osx-64::statsmodels-0.11.1-py36h37b9a7d_1
  tbb                conda-forge/osx-64::tbb-2019.9-ha1b3eb9_1
  texttable          conda-forge/noarch::texttable-1.6.2-py_0
  tk                 conda-forge/osx-64::tk-8.6.10-hbbe82c9_0
  tornado            conda-forge/osx-64::tornado-6.0.4-py36h37b9a7d_1
  tqdm               bioconda/osx-64::tqdm-4.7.2-py36_0
  umap-learn         conda-forge/osx-64::umap-learn-0.4.2-py36h9f0ad1d_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/osx-64::xz-5.2.5-h0b31af3_0
  zipp               conda-forge/noarch::zipp-3.1.0-py_0
  zlib               conda-forge/osx-64::zlib-1.2.11-h0b31af3_1006


Proceed ([y]/n)? y


Downloading and Extracting Packages
tornado-6.0.4        | 639 KB    | ################################################################################################################ | 100%
pandas-1.0.3         | 10.2 MB   | ################################################################################################################ | 100%
python-levenshtein-0 | 67 KB     | ################################################################################################################ | 100%
llvm-openmp-10.0.0   | 268 KB    | ################################################################################################################ | 100%
packaging-20.1       | 31 KB     | ################################################################################################################ | 100%
xz-5.2.5             | 266 KB    | ################################################################################################################ | 100%
scipy-1.4.1          | 19.0 MB   | ################################################################################################################ | 100%
scanpy-1.4.6         | 6.6 MB    | ################################################################################################################ | 100%
python-3.6.10        | 20.2 MB   | ################################################################################################################ | 100%
parasail-python-1.2  | 1.9 MB    | ################################################################################################################ | 100%
mock-3.0.5           | 44 KB     | ################################################################################################################ | 100%
pytables-3.6.1       | 1.4 MB    | ################################################################################################################ | 100%
anndata-0.7.1        | 155 KB    | ################################################################################################################ | 100%
importlib-metadata-1 | 42 KB     | ################################################################################################################ | 100%
kiwisolver-1.2.0     | 57 KB     | ################################################################################################################ | 100%
numba-0.48.0         | 3.2 MB    | ################################################################################################################ | 100%
python-igraph-0.8.2  | 2.0 MB    | ################################################################################################################ | 100%
blosc-1.18.1         | 859 KB    | ################################################################################################################ | 100%
scikit-learn-0.22.2. | 6.4 MB    | ################################################################################################################ | 100%
matplotlib-base-3.2. | 7.1 MB    | ################################################################################################################ | 100%
setuptools-46.1.3    | 635 KB    | ################################################################################################################ | 100%
importlib_metadata-1 | 3 KB      | ################################################################################################################ | 100%
tbb-2019.9           | 157 KB    | ################################################################################################################ | 100%
pytz-2020.1          | 227 KB    | ################################################################################################################ | 100%
scirpy-0.1.2         | 51 KB     | ################################################################################################################ | 100%
glib-2.64.2          | 3.2 MB    | ################################################################################################################ | 100%
nose-1.3.7           | 213 KB    | ################################################################################################################ | 100%
pyparsing-2.4.7      | 60 KB     | ################################################################################################################ | 100%
numexpr-2.7.1        | 128 KB    | ################################################################################################################ | 100%
openssl-1.1.1g       | 1.9 MB    | ################################################################################################################ | 100%
umap-learn-0.4.2     | 108 KB    | ################################################################################################################ | 100%
statsmodels-0.11.1   | 9.6 MB    | ################################################################################################################ | 100%
squarify-0.4.3       | 7 KB      | ################################################################################################################ | 100%
llvmlite-0.31.0      | 251 KB    | ################################################################################################################ | 100%
h5py-2.10.0          | 1020 KB   | ################################################################################################################ | 100%
libcxx-10.0.0        | 1.0 MB    | ################################################################################################################ | 100%
setuptools_scm-3.5.0 | 3 KB      | ################################################################################################################ | 100%
pip-20.1             | 1.1 MB    | ################################################################################################################ | 100%
seaborn-0.10.1       | 158 KB    | ################################################################################################################ | 100%
cython-0.29.17       | 2.1 MB    | ################################################################################################################ | 100%
legacy-api-wrap-1.2  | 18 KB     | ################################################################################################################ | 100%
setuptools-scm-3.5.0 | 23 KB     | ################################################################################################################ | 100%
pycairo-1.19.1       | 69 KB     | ################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate playground_scirpy
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) Federicos-MBP:Development fede$ conda activate playground_scirpy
(playground_scirpy) Federicos-MBP:Development fede$ python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:27:41)
[GCC Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scirpy as ir
/Users/fede/miniconda3/envs/playground_scirpy/lib/python3.6/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fede/miniconda3/envs/playground_scirpy/lib/python3.6/site-packages/scirpy/__init__.py", line 9, in <module>
    from scanpy import AnnData, read_h5ad
  File "/Users/fede/miniconda3/envs/playground_scirpy/lib/python3.6/site-packages/scanpy/__init__.py", line 39, in <module>
    from . import datasets, logging, queries, external, get
  File "/Users/fede/miniconda3/envs/playground_scirpy/lib/python3.6/site-packages/scanpy/datasets/__init__.py", line 3, in <module>
    from ._datasets import (
  File "/Users/fede/miniconda3/envs/playground_scirpy/lib/python3.6/site-packages/scanpy/datasets/_datasets.py", line 7, in <module>
    from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm.auto'

###################################
```
I could resolve this by

```
pip install -U tqdm
```

Could this be needed to be included in the conda recipe?

**Comment by grst** [comment]
- [ ] check conda recipe
- [ ] create CI test for conda

**Comment by grst** [comment]
Ideally this was fixed upstream in scanpy (https://github.com/theislab/scanpy/issues/1244). 
Until then, will require minimal version of tqdm in scirpy.
