### ISSUE TITLE
clonotype_imbalance not found in conda package. 

### ISSUE THREAD

**Issue by grst** [icbi-lab/scirpy#129]
- Another thing I encountered was the following, when trying out the full run of the tutorial with the 3k subset of data
```
###################################

>>> ir.pl.clonotype_imbalance(adata, replicate_col='sample', groupby='source', case_label='Tumor', additional_hue='site', plot_type='strip')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scirpy._plotting' has no attribute 'clonotype_imbalance'
>>> ir.pl.clonotype_imbalance(adata, replicate_col='sample', groupby='source', case_label='Tumor', additional_hue='diagnosis', plot_type='volcano')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scirpy._plotting' has no attribute 'clonotype_imbalance'

>>> ir.pl.
ir.pl.COLORMAP_EDGES(            ir.pl.clonal_expansion(          ir.pl.embedding(                 ir.pl.spectratype(
ir.pl.alpha_diversity(           ir.pl.clonotype_network(         ir.pl.group_abundance(           ir.pl.vdj_usage(
ir.pl.base                       ir.pl.clonotype_network_igraph(  ir.pl.repertoire_overlap(       


>>> print(ir.__version__)
0.0.0

###################################
```
Looks like the function is not found?
Double checking with conda, the recipe is correctly listed in its version, but is not displayed when printing the info in the console.

**Comment by grst** [comment]
might simply note have been part of the last release. Will make sure it's in the next one.
