### ISSUE TITLE
clonotype_network ERROR

### ISSUE THREAD

**Issue by bio-liucheng** [icbi-lab/scirpy#137]
Hi developer,

I followed the wu2020_3k tutorial and came out with this error.

```
>>> ir.tl.define_clonotypes(adata)
>>> ir.tl.clonotype_network(adata, min_size=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\scirpy\_tools\_clonotypes.py", line 219, in clonotype_network
    coords = layout_components(graph, **layout_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scirpy\util\graph.py", line 97, in layout_components
    coords = np.vstack(component_layouts)[vertex_sorter, :]
  File "<__array_function__ internals>", line 6, in vstack
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

```

Here are my packages versions:
```
scirpy==0.2 
>>> sc.logging.print_versions()
scanpy==1.5.1 anndata==0.7.3 umap==0.3.10 numpy==1.18.4 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.23.1 statsmodels==0.11.1 python-igraph==0.7.1 louvain==0.6.1 leidenalg==0.7.0

```

I run this tutorial on windows. In the previous version (v0.1.2), it was no problem to run these codes.

How can I fix this?

Thank you.

**Comment by grst** [comment]
Hi @bio-liucheng, 

thanks for reporting this!

I believe the reason you could previously run this without errors is that the default layout changed from `fr` to `components`. 
Could you please try to run 
```python
ir.tl.clonotype_network(adata, min_size=2, layout='fr')
```
to verify if this is the case? 

--- 
But, of course, the `component` layout should work for you, too. 
Could you please report the following values right before running `clonotype_network`? 
```python
adata.shape
adata.obs["clonotype"].unique().size
np.sum(adata.obs["clonotype_size"] >= 2)
```

Cheers, 
Gregor

**Comment by bio-liucheng** [comment]
Hi Gregor,

Thank you for your reply!

Here are my reports and codes

```
>>> adata
AnnData object with n_obs × n_vars = 2979 × 30727
    obs: 'cluster_orig', 'patient', 'sample', 'source', 'clonotype_orig', 'multi_chain', 'TRA_1_cdr3', 'TRA_2_cdr3', 'TRB_1_cdr3', 'TRB_2_cdr3', 'TRA_1_junction_ins', 'TRA_2_junction_ins', 'TRB_1_junction_ins', 'TRB_2_junction_ins', 'TRA_1_expr', 'TRA_2_expr', 'TRB_1_expr', 'TRB_2_expr', 'TRA_1_v_gene', 'TRA_2_v_gene', 'TRB_1_v_gene', 'TRB_2_v_gene', 'TRA_1_d_gene', 'TRA_2_d_gene', 'TRB_1_d_gene', 'TRB_2_d_gene', 'TRA_1_j_gene', 'TRA_2_j_gene', 'TRB_1_j_gene', 'TRB_2_j_gene', 'TRA_1_c_gene', 'TRA_2_c_gene', 'TRB_1_c_gene', 'TRB_2_c_gene', 'TRA_1_cdr3_nt', 'TRA_2_cdr3_nt', 'TRB_1_cdr3_nt', 'TRB_2_cdr3_nt', 'has_tcr', 'batch', 'chain_pairing', 'clonotype', 'clonotype_size'
    var: 'gene_ids', 'feature_types'
    uns: 'cluster_orig_colors', 'multi_chain_colors', 'tcr_neighbors'
    obsm: 'X_umap_orig', 'X_umap'
>>> adata.shape
(2979, 30727)
>>> adata.obs["clonotype"].unique().size
2504
>>> np.sum(adata.obs["clonotype_size"] >= 2)
697
>>> ir.tl.clonotype_network(adata, min_size=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\scirpy\_tools\_clonotypes.py", line 219, in clonotype_network
    coords = layout_components(graph, **layout_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\scirpy\util\graph.py", line 97, in layout_components
    coords = np.vstack(component_layouts)[vertex_sorter, :]
  File "<__array_function__ internals>", line 6, in vstack
  File "C:\ProgramData\Miniconda3\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
>>> ir.tl.clonotype_network(adata, min_size=2, layout='fr')
>>> ir.pl.clonotype_network(adata, color="clonotype", legend_loc="none")
```

It worked when I set `layout='fr'` and report errors using the default. 

Best,
Cheng

**Comment by grst** [comment]
Hi Cheng, 

unfortunately, I was not able to reproduce your issue. 

For futher investigation, could you please try the following/provide the following information:
 * delete the `data` folder and the `wu2020_3k.h5ad` within (it will automatically re-download). It could simply be that you have an old version of the data. 
 * Do you *exactely* run the commands from the tutorial, in the same order, or do you do something (even slightly) different? If so, could you please provide the exact commands you run from the point you start python until the error occurs?
 * I might need more information about your environment. Could you provide the output of `pip freeze` (when using pip) or `conda env export` (when using conda)? 

Thanks, 
Gregor

**Comment by bio-liucheng** [comment]
Hi Gregor,

Sorry for bothering you about this issue. Finally, I solved this problem. Maybe the environment conflicts between packages.

When I use `pip freeze`, some warning reported.

```
F:\>pip freeze > requirements.txt
WARNING: Could not generate requirement for distribution -5py 2.10.0 (c:\programdata\miniconda3\lib\site-packages): Parse error at "'-5py==2.'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -umpy 1.18.2 (c:\programdata\miniconda3\lib\site-packages): Parse error at "'-umpy==1'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -phinx 2.4.4 (c:\programdata\miniconda3\lib\site-packages): Parse error at "'-phinx=='": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -nndata 0.7.1 (c:\programdata\miniconda3\lib\site-packages): Parse error at "'-nndata='": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution - ndas (c:\programdata\miniconda3\lib\site-packages): Parse error at "'-===ndas'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -canpy 1.5.1 (c:\programdata\miniconda3\lib\site-packages): Parse error at "'-canpy=='": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -atplotlib 3.2.1 (c:\programdata\miniconda3\lib\site-packages): Parse error at "'-atplotl'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -andas 0.25.1 (c:\programdata\miniconda3\lib\site-packages): Parse error at "'-andas=='": Expected W:(abcd...)
```

So I used conda to create a new environment and reinstall scirpy. It is successfully running as the tutorial described. Scirpy is a very powerful package to manage TCR data! 

Thanks for your help again.

Best,
Cheng

**Comment by grst** [comment]
Glad you found a solution! There really seems to be something wrong with that environment... 

Feel free to contact me again if you encounter issues or have suggestions!

Best, 
Gregor
