### ISSUE TITLE
OSErrors while running ir.pp.ir_neighbors

### ISSUE THREAD

**Issue by Richard0146** [icbi-lab/scirpy#233]
I am learning to use Scirpy to deal with single cell immune profiling and facing a problem:

OSError: [Errno 22] Invalid argument: 'D:\\immune\\<input>'
in
```
ir.pp.ir_neighbors(adata, metric="hamming", sequence="aa", cutoff=2,
                   receptor_arms="all", dual_ir="primary_only")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 234, in _get_code_from_file
    with io.open_code(decoded_path) as f:
OSError: [Errno 22] Invalid argument: 'D:\\immune\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 234, in _get_code_from_file
    with io.open_code(decoded_path) as f:
OSError: [Errno 22] Invalid argument: 'D:\\immune\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "C:\Users\Ribose\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Permission denied
```

The content of my adata.obs shown following:
```
adata.obs.columns
Index(['IR_VJ_1_locus', 'IR_VJ_2_locus', 'IR_VDJ_1_locus', 'IR_VDJ_2_locus',
       'IR_VJ_1_cdr3', 'IR_VJ_2_cdr3', 'IR_VDJ_1_cdr3', 'IR_VDJ_2_cdr3',
       'IR_VJ_1_cdr3_nt', 'IR_VJ_2_cdr3_nt', 'IR_VDJ_1_cdr3_nt',
       'IR_VDJ_2_cdr3_nt', 'IR_VJ_1_expr', 'IR_VJ_2_expr', 'IR_VDJ_1_expr',
       'IR_VDJ_2_expr', 'IR_VJ_1_expr_raw', 'IR_VJ_2_expr_raw',
       'IR_VDJ_1_expr_raw', 'IR_VDJ_2_expr_raw', 'IR_VJ_1_v_gene',
       'IR_VJ_2_v_gene', 'IR_VDJ_1_v_gene', 'IR_VDJ_2_v_gene',
       'IR_VJ_1_d_gene', 'IR_VJ_2_d_gene', 'IR_VDJ_1_d_gene',
       'IR_VDJ_2_d_gene', 'IR_VJ_1_j_gene', 'IR_VJ_2_j_gene',
       'IR_VDJ_1_j_gene', 'IR_VDJ_2_j_gene', 'IR_VJ_1_c_gene',
       'IR_VJ_2_c_gene', 'IR_VDJ_1_c_gene', 'IR_VDJ_2_c_gene',
       'IR_VJ_1_junction_ins', 'IR_VJ_2_junction_ins', 'IR_VDJ_1_junction_ins',
       'IR_VDJ_2_junction_ins', 'has_ir', 'multi_chain', 'receptor_type',
       'receptor_subtype', 'chain_pairing'],
      dtype='object')
```

What is the reason causing the error and how to deal with it? Thanks.

**Comment by grst** [comment]
You might actually be running into a Python bug:
https://stackoverflow.com/questions/54176876/what-is-the-reason-of-this-errror-permissionerror-winerror-5-access-is-deni

Whats your python version? And can you try upgrading to python 3.7.9 or 3.8.7 (python 3.9 is not yet supported)?

**Comment by Richard0146** [comment]
my python version is 3.8.7. Should I try python 3.7.9?

**Comment by Richard0146** [comment]
I just try to run this sentence in IDLE and the problem is solved. 
Python console in PyCharm cannot run it successfully. Maybe it is due to the bug of python or PyCharm.

**Comment by grst** [comment]
No, that bug should be fixed in both versions... But it really seems like some low-level problem with the multiprocessing package. 

More things you could try:
 * setting `n_jobs=1` in `ir_neighbors` to make it run single-threaded. 
 * re-install python and scirpy from scratch. Ideally using [miniconda](https://docs.conda.io/en/latest/miniconda.html)

**Comment by grst** [comment]
>  Python console in PyCharm cannot run it successfully. Maybe it is due to the bug of python or PyCharm.

weird. Are you sure the python version used in pycharm is also 3.8.7?

**Comment by Richard0146** [comment]
I just used `sys.version` to check the python version in PyCharm and the result is,
```
'3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
```

I also added `n_jobs=1` in `ir_neighbors`, and it returns the same error with a "infinite loop"

**Comment by grst** [comment]
Maybe it's indeed a Pycharm issue:
https://youtrack.jetbrains.com/issue/PY-36151

**Comment by Richard0146** [comment]
I may change an IDE to do this project. Thanks for your reply.
