### ISSUE TITLE
TypeError while running pp.ir_neighbors

### ISSUE THREAD

**Issue by Richard0146** [icbi-lab/scirpy#236]
TypeError was raised when I run the following script.

```python
import sys
import os
from anndata import AnnData
sys.path.insert(0, "../..")

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scirpy as ir
import scanpy as sc
from glob import glob
import pandas as pd
import tarfile
import anndata
import warnings
from numba import NumbaPerformanceWarning

# ignore numba performance warnings
warnings.filterwarnings("ignore", category=NumbaPerformanceWarning)

# suppress "storing XXX as categorical" warnings.
anndata.logging.anndata_logger.setLevel("ERROR")

class VDJprocessing():
    def __init__(self, folder="C:/Users/Ribose/Desktop/BC10_TUMOR1/",
                 raw_path="undel_results.h5ad",
                 result_path="results.h5ad"):

        self.vdjdata = os.path.join(folder, 'filtered_contig_annotations.csv')
        self.gexdata = os.path.join(folder, 'filtered_feature_bc_matrix')

        self.BCRundel = os.path.join(folder, raw_path)
        self.BCRdata = os.path.join(folder, result_path)

    def preprocessing(self):

        self.adata_tcr = ir.io.read_10x_vdj(self.vdjdata)
        self.adata = sc.read_10x_mtx(self.gexdata, cache=True, 
                                     var_names='gene_symbols')

        # TCR Processing
        ir.pp.merge_with_ir(self.adata, self.adata_tcr)
        ir.tl.chain_qc(self.adata)
        
         # file saving (undelete)
        self.adata.write(self.BCRundel)
                                  
        # GEX Processing
        sc.pp.normalize_total(self.adata, target_sum=1e4)
        sc.pp.log1p(self.adata)
        sc.pp.highly_variable_genes(self.adata, min_mean=0.0125, 
                                    max_mean=3, min_disp=0.5)

        sc.pp.scale(self.adata, max_value=10)
        sc.pp.pca(self.adata, svd_solver="arpack")
        sc.pp.neighbors(self.adata)
        sc.tl.tsne(self.adata, n_jobs=5)
        sc.tl.leiden(self.adata)

        # file saving
        self.adata.write(self.BCRdata)

    def primary_only(self):
        self.adata = self.adata[self.adata.obs["chain_pairing"] == "single pair", :].copy()

        # file saving
        self.adata.write(self.BCRdata)
    def TCRplot_pre(self, cluster_size=3, metric="hamming", 
                    sequence="aa", cutoff=None):

        self.adata = ir.io.read_h5ad(self.BCRdata)

        ir.pp.ir_neighbors(self.adata)
        ir.tl.define_clonotypes(self.adata, same_v_gene="all")

        if cutoff == None:
            if metric == "hamming":
                ir.pp.ir_neighbors(self.adata, metric=metric, sequence=sequence, 
                                   cutoff=2, receptor_arms="all", n_jobs=4)
        else:
            ir.pp.ir_neighbors(self.adata, metric=metric, sequence=sequence, 
                               cutoff=cutoff, receptor_arms="all", n_jobs=4)  # cluster method, sequence choosing

        ir.tl.define_clonotype_clusters(self.adata, partitions="connected",
                                        sequence=sequence, metric=metric)  # 不能用pycharm执行

        ir.tl.clonotype_network(self.adata, min_size=cluster_size, 
                                sequence=sequence, metric=metric)  # return ax list
        
        # file saving
        self.adata.write(self.BCRdata)

if __name__ == '__main__':

    VDJ = VDJprocessing()
    VDJ.preprocessing()
    VDJ.primary_only()
    VDJ.TCRplot_pre()
```
and it returned:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ribose\AppData\Roaming\Python\Python38\site-packages\scirpy\_tools\_clonotypes.py", line 131, in define_clonotypes
    return _define_clonotypes(adata, key_added=key_added, **kwargs)
  File "C:\Users\Ribose\AppData\Roaming\Python\Python38\site-packages\scirpy\_tools\_clonotypes.py", line 161, in _define_clonotypes
    g = _get_igraph_from_adjacency(conn)
  File "C:\Users\Ribose\AppData\Roaming\Python\Python38\site-packages\scirpy\util\graph.py", line 30, in _get_igraph_from_adjacency
    g.es["weight"] = weights
  File "C:\Users\Ribose\AppData\Roaming\Python\Python38\site-packages\scipy\sparse\base.py", line 291, in __len__
    raise TypeError("sparse matrix length is ambiguous; use getnnz()"
TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]
```
Could you please tell me why this error was raised and how to solve it? Thank you.

**Comment by grst** [comment]
What's your scipy and numpy versions? 
You can for instance use [scanpy.logging.print_versions()](https://scanpy.readthedocs.io/en/stable/api/scanpy.logging.print_versions.html#scanpy.logging.print_versions)

**Comment by Richard0146** [comment]
Hi. The results is
```
WARNING: If you miss a compact list, please try `print_header`!
-----
anndata     0.7.5
scanpy      1.6.1
sinfo       0.3.1
-----
Levenshtein                 NA
PIL                         8.1.0
airr                        1.3.1
anndata                     0.7.5
cairo                       1.20.0
cffi                        1.14.4
constants                   NA
cycler                      0.10.0
cython_runtime              NA
dateutil                    2.8.1
get_version                 2.1
h5py                        3.1.0
highs_wrapper               NA
igraph                      0.8.3
joblib                      1.0.0
kiwisolver                  1.3.1
legacy_api_wrap             1.2
leidenalg                   0.8.3
llvmlite                    0.35.0
matplotlib                  3.3.3
mpl_toolkits                NA
natsort                     7.1.0
nt                          NA
numba                       0.52.0
numexpr                     2.7.2
numpy                       1.19.5
packaging                   20.8
pandas                      1.2.0
parasail                    1.2.3
pkg_resources               NA
pyparsing                   2.4.7
pytoml                      NA
pytz                        2020.5
scanpy                      1.6.1
scipy                       1.6.0
scirpy                      0.6.0
seaborn                     0.11.1
setuptools_scm              NA
sinfo                       0.3.1
six                         1.15.0
sklearn                     0.24.0
statsmodels                 0.12.1
tables                      3.6.1
texttable                   1.6.3
tqdm                        4.56.0
tracerlib                   NA
yaml                        5.3.1
yamlordereddictloader       NA
-----
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
Windows-10-10.0.18362-SP0
8 logical CPU cores, Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
-----
Session information updated at 2021-01-28 13:37
```

**Comment by grst** [comment]
Thanks for the additional information! 
I believe this happens if none of your cells is connected in the clonotype neighborhood graph. 

I'll post a fix shortly.

**Comment by grst** [comment]
This should be solved in #238. 
Can you try it out with the development version? You can install it using
```
pip install git+https://github.com/icbi-lab/scirpy.git@fix-236
```

**Comment by Richard0146** [comment]
Thank you for your help. Indeed, this data has only 22 cells, so it is very likely that there are no connections in the neighbor images.

I am executing the command you sent me in windows cmd and this seems to take some time. Command `pip install git+https://github.com/icbi-lab/scirpy.git@fix-236` has been executing for 10 minutes now and I don't know if this is normal.

Also in the github interface (this image below), it suggests that
```Some checks were not successful
17 failing, 1 successful, and 1 action required checks```

What's this mean and will this cause my pull process to fail?
Please forgive me if I am not very familiar with github. Thanks for your patience and explanation!

![image](https://user-images.githubusercontent.com/47129689/106354413-984fa780-632c-11eb-90ce-aac9af563953.png)

**Comment by grst** [comment]
Yes it will compile parasail from scratch, that will take some while. But it eventually failed for me as well, that's why I deleted the message again. 

I'm currently working on the failing tests, but they are unrelated to the issue you were having.

**Comment by grst** [comment]
The tests are now passing and `pip install git+https://github.com/icbi-lab/scirpy.git@fix-236` works for me as expected. 
Did it eventually finish for you?

**Comment by Richard0146** [comment]
Thanks for your help. The command just waited for a long time but did not work and reported an error, so I did not try again. Now I executed the command again and waiting for the result in progress.

**Comment by Richard0146** [comment]
I ran the command `pip install git+https://github.com/icbi-lab/scirpy.git@fix-236` twice but it reported the same error:
````
Collecting git+https://github.com/icbi-lab/scirpy.git@fix-236
  Cloning https://github.com/icbi-lab/scirpy.git (to revision fix-236) to c:\users\ribose\appdata\local\temp\pip-req-build-22ifa4gn
ERROR: Command errored out with exit status 128: git clone -q https://github.com/icbi-lab/scirpy.git 'C:\Users\Ribose\AppData\Local\Temp\pip-req-build-22ifa4gn' Check the logs for full command output.
```

**Comment by grst** [comment]
Weird, it already fails during cloning the repository. 
Whatever,I'm just gonna make a release, then you can install it in the regular way.

**Comment by Richard0146** [comment]
So should I just wait for you to release the latest version of the package now and then execute `pip install --upgrade scirpy`?
Should I re-try `pip install git+https://github.com/icbi-lab/scirpy.git@fix-236` or to see the pip failing log?

**Comment by grst** [comment]
```
pip install --upgrade scirpy
```

should work now and install v0.6.1.
