### ISSUE TITLE
merge/concatenate gene expression .h5 files

### ISSUE THREAD

**Issue by hchintalapudi** [icbi-lab/scirpy#289]
hi,
Thanks for the amazing tool.

I'm trying to read 5 samples' airrseq files and gex files using 'ir.io.read_10x_vdj' and 'sc.read_10x_h5' respectively.
Then integrate the merged objects using 'ir.pp.merge_with_ir'
I can succesfully concatenate the airrseq data usiung '.concatenate' but I get an error when I do the same with the gex/RNAseq .h5 files.

```
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Traceback (most recent call last):
  File "/gstore/home/chintalh/scirpy_tmp.py", line 16, in <module>
    data_gex = data_gex1.concatenate(data_gex2, data_gex3, data_gex4, data_gex5)
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py", line 1757, in concatenate
    out = concat(
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/merge.py", line 818, in concat
    alt_annot = merge_dataframes(
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/merge.py", line 531, in merge_dataframes
    dfs = [df.reindex(index=new_index) for df in dfs]
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/merge.py", line 531, in <listcomp>
    dfs = [df.reindex(index=new_index) for df in dfs]
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/pandas/util/_decorators.py", line 324, in wrapper
    return func(*args, **kwargs)
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/pandas/core/frame.py", line 4767, in reindex
    return super().reindex(**kwargs)
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/pandas/core/generic.py", line 4809, in reindex
    return self._reindex_axes(
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/pandas/core/frame.py", line 4592, in _reindex_axes
    frame = frame._reindex_index(
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/pandas/core/frame.py", line 4611, in _reindex_index
    return self._reindex_with_indexers(
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/pandas/core/generic.py", line 4874, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 666, in reindex_indexer
    self.axes[axis]._validate_can_reindex(indexer)
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3785, in _validate_can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

```
Here's  my code:
```
#!/usr/bin/env python
import scanpy as sc
import scirpy as ir
import numpy as np
data1 = ir.io.read_10x_vdj("/gstore/data/genomics/congee_rest_runs/60eefd86a2285de000dec387/LIB5437928_SAM24396521/output/airrseq_10x/6a190d9e-181a-449e-bd43-5a3ab6bb4e04/call-consolidated_output/execution/LIB5437928_SAM24396521/vdj_outs/all_contig_annotations.csv")

data2 = ir.io.read_10x_vdj("/gstore/data/genomics/congee_rest_runs/60eefd86a2285de000dec387/LIB5437926_SAM24396520/output/airrseq_10x/88a6c238-f13c-4ca2-8e03-1407964cadb2/call-consolidated_output/execution/LIB5437926_SAM24396520/vdj_outs/all_contig_annotations.csv")

data3 = ir.io.read_10x_vdj("/gstore/data/genomics/congee_rest_runs/60eefd86a2285de000dec387/LIB5437924_SAM24396519/output/airrseq_10x/e91a811a-d224-4d5a-896b-8e597a8b1582/call-consolidated_output/execution/LIB5437924_SAM24396519/vdj_outs/all_contig_annotations.csv")

data4 = ir.io.read_10x_vdj("/gstore/data/genomics/congee_rest_runs/60eefd86a2285de000dec387/LIB5437930_SAM24396522/output/airrseq_10x/f41965bf-e0c3-4b97-a7ee-866b0c27a3b0/call-consolidated_output/execution/LIB5437930_SAM24396522/vdj_outs/all_contig_annotations.csv")

data5 = ir.io.read_10x_vdj("/gstore/data/genomics/congee_rest_runs/60eefd86a2285de000dec387/LIB5437932_SAM24396523/output/airrseq_10x/43d01408-8b1f-4ae8-a7d6-56d07376d647/call-consolidated_output/execution/LIB5437932_SAM24396523/vdj_outs/all_contig_annotations.csv")


cat=['SAM24396521','SAM24396520','SAM24396519','SAM24396522','SAM24396523']
data_tcr = data1.concatenate(data2, data3, data4, data5, batch_key='Sample', batch_categories=cat)

#########
data_gex1 = sc.read_10x_h5("/gstore/data/genomics/congee_rest_runs/60ba4af7a2285de000d9d442/SAM24396521/output/cellranger_count_601/86f080b1-2b8d-4af5-b934-e215f362045a/call-run_cellranger_count/shard-0/execution/LIB5437929_SAM24396521/outs/filtered_feature_bc_matrix.h5")
#data_gex1.var_names_make_unique()
data_gex2 = sc.read_10x_h5("/gstore/data/genomics/congee_rest_runs/60bfb4e7a2285de000da35db/SAM24396520/output/cellranger_count_601/4582a707-75fa-4720-9054-49ffb9b389f6/call-run_cellranger_count/shard-0/execution/LIB5437927_SAM24396520/outs/filtered_feature_bc_matrix.h5")
#data_gex2.var_names_make_unique()
data_gex3 = sc.read_10x_h5("/gstore/data/genomics/congee_rest_runs/60bfb4e7a2285de000da35db/SAM24396519/output/cellranger_count_601/770eeaed-72a4-4402-8471-d654f7cd325d/call-run_cellranger_count/shard-0/execution/LIB5437925_SAM24396519/outs/filtered_feature_bc_matrix.h5")
#data_gex3.var_names_make_unique()
data_gex4 = sc.read_10x_h5("/gstore/data/genomics/congee_rest_runs/60bfb4e7a2285de000da35db/SAM24396522/output/cellranger_count_601/f6389e38-5f08-421e-9028-8bd25815e13e/call-run_cellranger_count/shard-0/execution/LIB5437931_SAM24396522/outs/filtered_feature_bc_matrix.h5")
#data_gex4.var_names_make_unique()
data_gex5 = sc.read_10x_h5("/gstore/data/genomics/congee_rest_runs/60bfb4e7a2285de000da35db/SAM24396523/output/cellranger_count_601/0752c4ea-3449-4df3-9872-08e48fbd77a9/call-run_cellranger_count/shard-0/execution/LIB5437933_SAM24396523/outs/filtered_feature_bc_matrix.h5")
#data_gex5.var_names_make_unique()

#data_gex = data_gex1.concatenate(data_gex2, data_gex3, data_gex4, data_gex5, batch_key='data_gex', batch_categories=gex_filenames)
data_gex = data_gex1.concatenate(data_gex2, data_gex3, data_gex4, data_gex5)
```
ANy tips apppreciated, thanks!

**Comment by grst** [comment]
Hi @hchintalapudi, 

sorry for the delayed feedback, I was on holiday the last week. 
Since you are having trouble concatenating the gene expression data, this looks more like a problem with anndata rather than with scirpy.

Yet, here are two comments on your code: 

1. I would recommend to first do `merge_with_ir` on each sample, and concatenate the merged samples in the end. This ensures that if barcodes are duplicate between samples they get the same suffix in both expression and TCR data. 
2. Instead of using `adata.concatenate` it is preferable to use the newer [`anndata.concat`](https://anndata.readthedocs.io/en/latest/anndata.concat.html#anndata.concat) function. 

Judging from your error message I believe something is wrong with the index of `adata.obs`. Have a look at `adata.obs` and `adata.obs.index` to check if something seems weird.

**Comment by hchintalapudi** [comment]
Thank you, @grst.
I'll give this a try and let you know how it goes.

**Comment by hchintalapudi** [comment]
Hi, @grst
I tried the [vignette](https://icbi-lab.github.io/scirpy/latest/tutorials/tutorial_io.html) where combining multiple samples is demonstrated.
Here is my code:
```
#!/usr/bin/env python
from glob import glob
import anndata as ad
import scanpy as sc
import scirpy as ir
import numpy as np


samples = {
    "SAM24396519": {"group": "D-2 (unactivated)"},
    "SAM24396520": {"group": "D0 (activated)"},
    "SAM24396521": {"group": "D+14 (TCR KO)"},
    "SAM24396522": {"group": "D+14 (WT1_52_13)"},
    "SAM24396523": {"group": "D+14 (WT1_REF)"},
}
# Create a list of AnnData objects (one for each sample)
adatas = []
for sample, sample_meta in samples.items():
    gex_file = glob(f"/gstore/home/chintalh/TCR-seq/*{sample}*.h5")[0]
    tcr_file = glob(f"/gstore/home/chintalh/TCR-seq/*{sample}*.csv")[0]
    adata = sc.read_10x_h5(gex_file)
    adata_tcr = ir.io.read_10x_vdj(tcr_file)
    ir.pp.merge_with_ir(adata, adata_tcr)
    adata.obs["sample"] = sample
    adata.obs["group"] = sample_meta["group"]
    # concatenation only works with unique gene names
    adata.var_names_make_unique()
    adatas.append(adata)

# Merge anndata objects
adata = ad.concat(adatas)

sc.pp.log1p(adata)
sc.pp.pca(adata, svd_solver="arpack")
sc.pp.neighbors(adata)
sc.tl.umap(adata)
sc.pl.umap(adata, color=["has_ir", "CD3E", "sample"], save="/gstore/home/chintalh/TCR-seq/UMAP_integrated.pdf")
```
I still get this error:

```
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
WARNING: Non-standard locus name ignored: Multi 
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'feature_types' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'genome' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/utils.py:111: UserWarning: Suffix used (-[0-9]+) to deduplicate index values may make index values difficult to interpret. There values with a similar suffixes in the index. Consider using a different delimiter by passing `join={delimiter}`Example key collisions generated by the make_index_unique algorithm: ['SNORD116-1', 'SNORD116-2', 'SNORD116-3', 'SNORD116-4', 'SNORD116-5']
  warnings.warn(
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
WARNING: Non-standard locus name ignored: Multi 
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'feature_types' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'genome' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/utils.py:111: UserWarning: Suffix used (-[0-9]+) to deduplicate index values may make index values difficult to interpret. There values with a similar suffixes in the index. Consider using a different delimiter by passing `join={delimiter}`Example key collisions generated by the make_index_unique algorithm: ['SNORD116-1', 'SNORD116-2', 'SNORD116-3', 'SNORD116-4', 'SNORD116-5']
  warnings.warn(
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
WARNING: Non-standard locus name ignored: Multi 
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'feature_types' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'genome' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/utils.py:111: UserWarning: Suffix used (-[0-9]+) to deduplicate index values may make index values difficult to interpret. There values with a similar suffixes in the index. Consider using a different delimiter by passing `join={delimiter}`Example key collisions generated by the make_index_unique algorithm: ['SNORD116-1', 'SNORD116-2', 'SNORD116-3', 'SNORD116-4', 'SNORD116-5']
  warnings.warn(
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
WARNING: Non-standard locus name ignored: Multi 
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'feature_types' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'genome' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/utils.py:111: UserWarning: Suffix used (-[0-9]+) to deduplicate index values may make index values difficult to interpret. There values with a similar suffixes in the index. Consider using a different delimiter by passing `join={delimiter}`Example key collisions generated by the make_index_unique algorithm: ['SNORD116-1', 'SNORD116-2', 'SNORD116-3', 'SNORD116-4', 'SNORD116-5']
  warnings.warn(
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.
WARNING: Non-standard locus name ignored: Multi 
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'feature_types' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/_core/anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
  c.reorder_categories(natsorted(c.categories), inplace=True)
... storing 'genome' as categorical
/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/anndata/utils.py:111: UserWarning: Suffix used (-[0-9]+) to deduplicate index values may make index values difficult to interpret. There values with a similar suffixes in the index. Consider using a different delimiter by passing `join={delimiter}`Example key collisions generated by the make_index_unique algorithm: ['SNORD116-1', 'SNORD116-2', 'SNORD116-3', 'SNORD116-4', 'SNORD116-5']
  warnings.warn(
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
Killed
```
Any idea, what might be going wrong here?
Thanks!

**Comment by grst** [comment]
I don't see an actual error message. Are you sure you didn't run out of memory or something like that?

**Comment by hchintalapudi** [comment]
I do not believe so.
Also, I did not get the plot when I used "save" in sc.pl.umap()

**Comment by grst** [comment]
> And it says 'Killed' below all the warnings, is this normal?

That's why I was thinking of "out of memory". If something goes wrong within python, you should usually get an Exception with stacktrace.

**Comment by hchintalapudi** [comment]
I'm running it in a script in a conda env I created just for scirpy.
I just scheduled it on Slurm to see if it's actually a memory issue, it ran without the ```Killed``` message.
I didn't know that generating that pdf would require that much memory.
Anyway, Issue solved: closing this.
Thanks again, @grst :)

**Comment by hchintalapudi** [comment]
Hi,
Sorry to bother again.
So, for this type of integrated analysis, would it make sense to do the TCR quality control and pre-processing of the expression data within the for-loop before merging with ```ir.pp.merge_with_ir()```?
Or do the QC functions work for TCR and exp work with the merged 'adata' object?
I ask as I'm getting errors when running ```ir.tl.define_clonotype_clusters()```:
```
Traceback (most recent call last):
  File "/gstore/home/chintalh/scripts/scirpy_example2.py", line 38, in <module>
    ir.tl.define_clonotype_clusters(
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/scirpy/io/_util.py", line 67, in check_wrapper
    return f(*args, **kwargs)
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/scirpy/_tools/_clonotypes.py", line 260, in define_clonotype_clusters
    ctn = ClonotypeNeighbors(
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/scirpy/ir_dist/_clonotype_neighbors.py", line 58, in __init__
    self._prepare(adata)
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/scirpy/ir_dist/_clonotype_neighbors.py", line 63, in _prepare
    self._make_clonotype_table(adata)
  File "/gstore/home/chintalh/miniconda3/envs/scirpy/lib/python3.9/site-packages/scirpy/ir_dist/_clonotype_neighbors.py", line 73, in _make_clonotype_table
    raise ValueError("Obs names need to be unique!")
ValueError: Obs names need to be unique!
``` 
Thanks.

**Comment by grst** [comment]
they work also on the integrated object.

The issue here is that your obs names (i.e. gene symbols) are not unique.

Try calling `adata.obs_names_make_unique()`.
Another option could be to use ensemble gene identifiers instead of gene
symbols.

Hope that helps!

**Comment by hchintalapudi** [comment]
Hi, 
Want some tips on another problem:
I can open a fresh issue if you want.
Basically I'm trying to plot clonotype network plots based on aa seq similarity:
```
ir.tl.chain_qc(adata)

ir.pp.ir_dist(adata, metric="alignment", sequence="aa", cutoff=25)
ir.tl.define_clonotypes(adata, receptor_arms="all", dual_ir="primary_only")

ir.tl.define_clonotype_clusters(
    adata,
    metric="alignment",
    sequence="aa",
    receptor_arms="any",
    dual_ir="primary_only",
)
ir.tl.clonotype_network(adata, size_aware=False, metric="alignment", sequence="aa")
ir.pl.clonotype_network(
    adata,
    color="cc_aa_alignment",
    base_size=20,
    panel_size=(7, 7),
    show_legend=False,
    show_size_legend=False
).get_figure().savefig('Integrated_clonotype_network.pdf', bbox_inches='tight')
```
And I get this fig which is cluttered and difficult to discern.
![Integrated_clonotype_network-1](https://user-images.githubusercontent.com/26474881/132913787-f3318664-cc74-4214-a87e-de7a6c164656.png)
How can I improve the figure?
Is it because of the large dataset?

I tried tweaking some parameters for the network graph in my previous run (before integration) 
based on nt seq similarity and it is relatively descent:
[clonotype_network.pdf](https://github.com/icbi-lab/scirpy/files/7146255/clonotype_network.pdf)
But the other one seems to be off no matter what I do.

Appreciate the help!

Thanks.

**Comment by grst** [comment]
The loops are due to a backwards incompatible change in the networkx
library.
This *should* be fixed in the latest version of scirpy, can you try
updating?

**Comment by hchintalapudi** [comment]
Update to 0.9.0?
I just updated on conda and I have 0.8.0
Will that work effectively?

**Comment by grst** [comment]
Update to 0.9.0?
>
Yes, you'll need v0.9!

I just updated on conda and I have 0.8.0
> Will that work effectively?
>
`conda upgrade --all` in your env should work. If not you can try to
install v0.9 explicitly:

`conda install "scirpy>=0.9.0"`
